/** export.js — .ics calendar export with proper timezone support (RFC 5545) */

/**
 * Format a Date as iCal local datetime string: 20260507T231700
 * @param {Date} date
 * @param {string} tz — IANA timezone, e.g. "Europe/Brussels"
 */
function fmtLocal(date, tz) {
  // Format in the target timezone
  const parts = new Intl.DateTimeFormat('en', {
    timeZone: tz,
    year:'numeric', month:'2-digit', day:'2-digit',
    hour:'2-digit', minute:'2-digit', second:'2-digit',
    hour12: false,
  }).formatToParts(date);
  const p = {};
  parts.forEach(({ type, value }) => { p[type] = value; });
  return `${p.year}${p.month}${p.day}T${p.hour}${p.minute}${p.second}`;
}

/** Format a Date as UTC iCal string: 20260507T211700Z */
function fmtUTC(date) {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

/** Format a Date as readable local time string: "23:17" */
function localTimeStr(date, tz) {
  return date.toLocaleTimeString('en-GB', {
    timeZone: tz, hour: '2-digit', minute: '2-digit',
  });
}

/** Format a Date as readable UTC time string: "21:17 UTC" */
function utcTimeStr(date) {
  return date.toUTCString().slice(17, 22) + ' UTC';
}

function esc(s) {
  return String(s ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;');
}

/**
 * Get the user's local IANA timezone.
 * Falls back to 'Europe/Brussels' for Belgian operators.
 */
export function getLocalTimezone() {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return tz || 'Europe/Brussels';
  } catch {
    return 'Europe/Brussels';
  }
}

/**
 * Generate an RFC 5545 .ics string with correct timezone.
 * Uses TZID so phone alarms fire at the right LOCAL time.
 *
 * @param {Array} events
 * @param {string} tz — IANA timezone string
 */
export function generateICS(events, tz = getLocalTimezone()) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Propagation Watch//ON3VZ//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    // Inline timezone component so ALL calendar apps interpret correctly
    'BEGIN:VTIMEZONE',
    `TZID:${tz}`,
    'BEGIN:STANDARD',
    'DTSTART:19701025T030000',
    'TZOFFSETFROM:+0200',
    'TZOFFSETTO:+0100',
    'TZNAME:CET',
    'END:STANDARD',
    'BEGIN:DAYLIGHT',
    'DTSTART:19700329T020000',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0200',
    'TZNAME:CEST',
    'END:DAYLIGHT',
    'END:VTIMEZONE',
  ];

  for (const ev of events) {
    const localStart = localTimeStr(ev.start, tz);
    const localEnd   = localTimeStr(ev.end,   tz);
    const utcStart   = utcTimeStr(ev.start);

    lines.push(
      'BEGIN:VEVENT',
      `UID:${ev.id ?? crypto.randomUUID()}@propagation-watch`,
      `DTSTAMP:${fmtUTC(new Date())}`,
      `DTSTART;TZID=${tz}:${fmtLocal(ev.start, tz)}`,
      `DTEND;TZID=${tz}:${fmtLocal(ev.end,   tz)}`,
      // Summary shows both UTC and local time
      `SUMMARY:${esc(ev.title)} — ${utcStart} / ${localStart} local`,
      `DESCRIPTION:${esc([
        ev.description ?? '',
        '',
        `Start: ${utcStart} (${localStart} ${tz})`,
        `End:   ${utcTimeStr(ev.end)} (${localEnd} ${tz})`,
        '',
        'Generated by Propagation Watch — on3vz.github.io/PropagationWatch',
      ].join('\n'))}`,
      `LOCATION:${esc(ev.location ?? '')}`,
      // Alarm fires 15 min before LOCAL start time
      'BEGIN:VALARM',
      'TRIGGER:-PT15M',
      'ACTION:DISPLAY',
      `DESCRIPTION:${esc(ev.title)} in 15 min — ${utcStart}`,
      'END:VALARM',
      'END:VEVENT'
    );
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

export function downloadICS(icsStr, filename = 'propagation-watch.ics') {
  const blob = new Blob([icsStr], { type: 'text/calendar;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Build a complete ICS from a watch + next window.
 * Duration defaults to 1 hour or until window reliability drops below threshold.
 */
export function watchWindowToICS(watch, window, tz = getLocalTimezone()) {
  const start = new Date(window.time);
  const end   = new Date(start.getTime() + 60 * 60 * 1000); // 1h default

  const utcStr   = utcTimeStr(start);
  const localStr = localTimeStr(start, tz);

  return generateICS([{
    id:          `${watch.id}-${start.getTime()}`,
    start,
    end,
    title:       `${watch.label} — ${watch.band} ${watch.mode}`,
    description: [
      `Band: ${watch.band}  Mode: ${watch.mode}`,
      `Expected reliability: ${Math.round(window.reliability * 100)}%`,
      `Bearing: ${watch.bearingShort}° (short path) / ${watch.bearingLong}° (long path)`,
      `Distance: ${watch.distanceKm.toLocaleString()} km`,
      `Grid: ${watch.grid}`,
    ].join('\n'),
    location: `${watch.name} (${watch.grid})`,
  }], tz);
}
